question_data = [
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "Coca-Cola's original colour was green.",
"correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "Popcorn was invented in 1871 by Frederick W. Rueckheim in the USA where he sold the snack on the streets of Chicago.",
"correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo. is a grammatically correct sentence.",
"correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "You are allowed to sell your soul on eBay.",
"correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "Sitting for more than three hours a day can cut two years off a person's life expectancy.",
"correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve meat by stuffing a chicken with snow.",
"correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "Fast food restaurant chains Carl's Jr. and Hardee's are owned by the same company.",
"correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "The French word to travel is Travail",
"correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "The average woman is 5 inches / 13 centimeters shorter than the average man.",
"correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "Haggis is traditionally ate on Burns Night.",
"correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "The word news originates from the first letters of the 4 main directions on a compass (North, East, West, South).",
"correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "An eggplant is a vegetable.",
"correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "Furby was released in 1998.",
"correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
"correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "The French word for glass is glace.",
"correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "Santa Claus is a variety of melon.",
"correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "Albert Einstein had trouble with mathematics when he was in school.",
"correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "Kissing someone for one minute burns about 2 calories.",
"correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
"question": "There are 86400 seconds in a day.",
"correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
 "question": "Sergio is a cutie pie.",
 "correct_answer": "True","incorrect_answers": ["False"]}
]